name: cup
channels:
  - pytorch
  - defaults
dependencies:
  - patchelf=0.15.0
  - pip=22.2.2
  - python=3.8.15
  - readline=8.2
  - setuptools=65.5.0
  - wheel=0.37.1
  - pip:
      - absl-py==1.3.0
      - adal==1.2.7
      - aiosignal==1.3.1
      - applicationinsights==0.11.10
      - argcomplete==1.12.3
      - asttokens==2.2.1
      - attrs==22.1.0
      - awscli==1.27.26
      - backcall==0.2.0
      - bcrypt==4.0.1
      - boto==2.49.0
      - boto3==1.26.26
      - botocore==1.29.26
      - box2d==2.3.10
      - box2d-kengz==2.3.3
      - cachetools==5.2.0
      - cffi==1.15.1
      - charset-normalizer==2.1.1
      - chex==0.1.5
      - click==8.0.4
      - cloudpickle==1.6.0
      - colorama==0.4.4
      - comm==0.1.2
      - crcmod==1.7
      - cryptography==38.0.4
      - cycler==0.11.0
      - cython==0.29.32
      - debugpy==1.6.6
      - decorator==5.1.1
      - distlib==0.3.6
      - dm-control==1.0.8
      - dm-env==1.5
      - dm-tree==0.1.7
      - docker-pycreds==0.4.0
      - docutils==0.16
      - doodad==0.3.0.dev0
      - einops==0.6.0
      - executing==1.2.0
      - fasteners==0.18
      - ffmpeg==1.4
      - ffprobe==0.5
      - filelock==3.8.2
      - flax==0.4.0
      - frozenlist==1.3.3
      - future==0.18.2
      - gdown==4.6.0
      - gitdb==4.0.10
      - gitpython==3.1.29
      - glfw==2.5.5
      - grpcio==1.51.3
      - gym==0.18.0
      - h5py==3.7.0
      - httplib2==0.21.0
      - humanfriendly==8.2
      - idna==3.4
      - imageio==2.9.0
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.1
      - ipykernel==6.21.3
      - ipython==8.7.0
      - isodate==0.6.1
      - jax==0.2.21
      - jaxlib==0.3.25
      - jedi==0.18.2
      - jmespath==1.0.1
      - joblib==0.14.1
      - jsonschema==4.17.3
      - jupyter-client==8.0.3
      - jupyter-core==5.2.0
      - kiwisolver==1.4.4
      - knack==0.7.2
      - labmaze==1.0.6
      - lxml==4.9.1
      - markdown==3.4.1
      - matplotlib==3.3.4
      - matplotlib-inline==0.1.6
      - mjrl==1.0.0
      - msal==1.0.0
      - msal-extensions==0.1.3
      - msgpack==1.0.4
      - msrest==0.7.1
      - msrestazure==0.6.4
      - mujoco==2.3.1.post1
      - mujoco-py==2.1.2.14
      - mypy-extensions==0.4.3
      - nest-asyncio==1.5.6
      - networkx==2.8.8
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optax==0.1.4
      - packaging==23.0
      - pandas==1.5.2
      - paramiko==2.12.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==7.2.0
      - pkginfo==1.9.2
      - pkgutil-resolve-name==1.3.10
      - platformdirs==2.6.0
      - portalocker==1.7.1
      - promise==2.3
      - prompt-toolkit==3.0.36
      - protobuf==3.20.3
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybullet==3.2.5
      - pycparser==2.21
      - pyglet==1.5.0
      - pygments==2.13.0
      - pyjwt==1.7.1
      - pynacl==1.5.0
      - pyopengl==3.1.6
      - pyopenssl==22.1.0
      - pyparsing==2.4.7
      - pyrsistent==0.19.2
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2022.6
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - pyzmq==25.0.1
      - ray==2.0.0
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.7.2
      - s3transfer==0.6.0
      - scikit-image==0.17.2
      - scikit-video==1.1.11
      - scipy==1.9.3
      - sentry-sdk==1.11.1
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.0
      - soupsieve==2.3.2.post1
      - stack-data==0.6.2
      - swig==4.1.0
      - tabulate==0.9.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - termcolor==2.1.1
      - tifffile==2022.10.10
      - toolz==0.12.0
      - torch==1.9.1+cu111
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.7.0
      - typed-argument-parser==1.7.2
      - typing-extensions==4.4.0
      - typing-inspect==0.8.0
      - uritemplate==4.1.1
      - urllib3==1.26.13
      - virtualenv==20.17.1
      - wandb==0.13.6
      - wcwidth==0.2.5
      - werkzeug==2.2.3
      - xmltodict==0.12.0
      - zipp==3.11.0
